'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Religion_Jeopardy.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property FinalJeo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FinalJeo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jeopardy_boardfill() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Jeopardy_boardfill", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Jeopardy_daily2x() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Jeopardy_daily2x", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Jeopardy_round_end() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Jeopardy_round_end", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Jeopardy_time() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Jeopardy_time", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property JeopardyAnimatedTitle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JeopardyAnimatedTitle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NOSORRY() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NOSORRY", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property religious_symbols() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("religious_symbols", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Think_Music() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Think_Music", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property this_is_jeopardy() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("this_is_jeopardy", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
